//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTSEntities1 : DbContext
    {
        public TTSEntities1()
            : base("name=TTSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChamCong> tblChamCongs { get; set; }
        public virtual DbSet<tblChucVu> tblChucVus { get; set; }
        public virtual DbSet<tblDuAn> tblDuAns { get; set; }
        public virtual DbSet<tblKhoaDaoTao> tblKhoaDaoTaos { get; set; }
        public virtual DbSet<tblNguoiPheDuyet> tblNguoiPheDuyets { get; set; }
        public virtual DbSet<tblNhanSuDA> tblNhanSuDAs { get; set; }
        public virtual DbSet<tblNhanXetNhiemVuDA> tblNhanXetNhiemVuDAs { get; set; }
        public virtual DbSet<tblNhiemVuDA> tblNhiemVuDAs { get; set; }
        public virtual DbSet<tblNhiemVuDaoTao> tblNhiemVuDaoTaos { get; set; }
        public virtual DbSet<tblPhongBan> tblPhongBans { get; set; }
        public virtual DbSet<tblQL> tblQLs { get; set; }
        public virtual DbSet<tblTrucThuoc> tblTrucThuocs { get; set; }
        public virtual DbSet<tblTT> tblTTS { get; set; }
        public virtual DbSet<tblYeuCau> tblYeuCaus { get; set; }
    }
}
