//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhoaDaoTao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKhoaDaoTao()
        {
            this.tblNhiemVuDaoTaos = new HashSet<tblNhiemVuDaoTao>();
        }
    
        public string MaKhoaDaoTao { get; set; }
        public string TenKhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhiemVuDaoTao> tblNhiemVuDaoTaos { get; set; }
    }
}
