//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanSuDA
    {
        public int MaNhanSuDA { get; set; }
        public string MaDA { get; set; }
        public string MaTTS { get; set; }
    
        public virtual tblDuAn tblDuAn { get; set; }
        public virtual tblTT tblTT { get; set; }
    }
}
