//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhiemVuDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhiemVuDA()
        {
            this.tblNhanXetNhiemVuDAs = new HashSet<tblNhanXetNhiemVuDA>();
        }
    
        public int MaNhiemVuDA { get; set; }
        public string MaDA { get; set; }
        public string MaTTS { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string NhiemVu { get; set; }
        public string status { get; set; }
    
        public virtual tblDuAn tblDuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhanXetNhiemVuDA> tblNhanXetNhiemVuDAs { get; set; }
        public virtual tblTT tblTT { get; set; }
    }
}
