//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhiemVuDaoTao
    {
        public int MaNhiemVuDaoTao { get; set; }
        public string MaKhoaDaoTao { get; set; }
        public string MaTTS { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string status { get; set; }
    
        public virtual tblKhoaDaoTao tblKhoaDaoTao { get; set; }
        public virtual tblTT tblTT { get; set; }
    }
}
