//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanXetNhiemVuDA
    {
        public int MaNhanXetNhiemVuDA { get; set; }
        public Nullable<int> MaNhiemVuDA { get; set; }
        public string NhanXet { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual tblNhiemVuDA tblNhiemVuDA { get; set; }
    }
}
