//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNguoiPheDuyet
    {
        public int MaPheDuyet { get; set; }
        public string MaQL { get; set; }
        public Nullable<int> MaYeuCau { get; set; }
    
        public virtual tblYeuCau tblYeuCau { get; set; }
        public virtual tblQL tblQL { get; set; }
    }
}
