//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQL()
        {
            this.tblNguoiPheDuyets = new HashSet<tblNguoiPheDuyet>();
        }
    
        public string MaQL { get; set; }
        public string TenQL { get; set; }
        public string MaPhongBan { get; set; }
        public string MaChucVu { get; set; }
        public string MatKhau { get; set; }
    
        public virtual tblChucVu tblChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNguoiPheDuyet> tblNguoiPheDuyets { get; set; }
        public virtual tblPhongBan tblPhongBan { get; set; }
    }
}
