//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVienThucTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTT()
        {
            this.tblChamCongs = new HashSet<tblChamCong>();
            this.tblNhanSuDAs = new HashSet<tblNhanSuDA>();
            this.tblNhiemVuDAs = new HashSet<tblNhiemVuDA>();
            this.tblNhiemVuDaoTaos = new HashSet<tblNhiemVuDaoTao>();
            this.tblYeuCaus = new HashSet<tblYeuCau>();
        }
    
        public string MaTTS { get; set; }
        public string TenTTS { get; set; }
        public string MaPhongBan { get; set; }
        public string MaChucVu { get; set; }
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChamCong> tblChamCongs { get; set; }
        public virtual tblChucVu tblChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhanSuDA> tblNhanSuDAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhiemVuDA> tblNhiemVuDAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhiemVuDaoTao> tblNhiemVuDaoTaos { get; set; }
        public virtual tblPhongBan tblPhongBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblYeuCau> tblYeuCaus { get; set; }
    }
}
